config/routes.rb
Rails.application.routes.draw do
  root 'players#index'

  devise_for :users, except: [:show]

  resources :players, except: [:edit, :update, :destroy]
  resources :matches, except: [:edit, :update, :destroy]
end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :home_player, class_name: 'Player'
  belongs_to :away_player, class_name: 'Player'

  validates_presence_of :match_date, :home_player_id, :home_score, :away_score,
                        :away_player_id
  validate :home_and_away_player, :future_date, :proper_score, :not_enough_goals

  def home_and_away_player
    errors.add(:base, "Home and Away player can't be the same") unless
      self.home_player_id != self.away_player_id
  end

  def future_date
    errors.add(:base, "Match Date can't be in the future") if
      self.match_date && self.match_date > Date.today
  end

  def proper_score
    errors.add(:base, "Only one player can have 10 goals") if
      self.away_score == 10 && self.home_score == 10
  end

  def not_enough_goals
    errors.add(:base, "One player must have 10 Goals") if
      (self.away_score && self.away_score < 10) && (self.home_score && self.home_score < 10)
  end
end

app/models/player.rb
class Player < ActiveRecord::Base
  has_many :home_score, foreign_key: :home_player_id, class_name: 'Match'
  has_many :away_score, foreign_key: :away_player_id, class_name: 'Match'

  validates_presence_of :first_name, :last_name
  validates :nickname, presence: true, uniqueness: { case_sensitive: false }

  mount_uploader :avatar, AvatarUploader

  default_scope -> { order(rating: :desc) }

  def full_name
    "#{first_name} #{last_name}"
  end

  def rank_measure
   # ((wins) / (wins + lose)) * number_of_matches # basic
   # algorith base on Lower bound of Wilson
    if wins > 0 or lose > 0
      self.rating = ((wins + 1.92) / (wins + lose) - 1.96 * Math.sqrt((wins * lose) / (wins + lose) + 0.96) /
          (wins + lose)) / (1 + 3.84 / (wins + lose))
    else
        0
    end
  end

  def rating
   self.rank_measure
  end

  def update_player_ranking
    self.update_attribute(:rating, rank_measure)
  end

  def home_player_match
    Match.where("home_player_id = ?", self.id)
  end

  def away_player_match
    Match.where("away_player_id = ?", self.id)
  end

  def home_score_sum
    home_player_match.sum(:home_score)
  end

  def away_score_sum
    away_player_match.sum(:away_score)
  end

  def number_of_matches
    Match.where("away_player_id = ? OR home_player_id = ?",
      self.id, self.id).count
  end

  def winner
      Match.where("(away_player_id = ? AND away_score = ?) OR
      (home_player_id = ? AND home_score = ?)", self.id, 10, self.id, 10)
  end

  def wins
    winner.count
  end

  def lost_game
    Match.where("(away_player_id = ? AND away_score BETWEEN ? and ?) OR
    (home_player_id = ? AND home_score BETWEEN ? and ?)",
    self.id, 1, 9, self.id, 1, 9)
  end

  def lose
    lost_game.count
  end

  def goals
    home_score_sum + away_score_sum
  end

  def lost_goals
    home_player_match.sum(:away_score) + away_player_match.sum(:home_score)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  protected
    def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:email, :password]
    devise_parameter_sanitizer.for(:account_update) << [:email, :password]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]

  def new
    @match = Match.new
  end

  def create
    @match = Match.new(match_params)

    if @match.save
      flash[:notice] = "Match has been successfully added"
      redirect_to root_url
    else
      flash.now[:danger] = "Match has not been added"
      render 'new'
    end
  end

  private

    def match_params
      params.require(:match).permit(:match_date, :home_player_id,
                            :away_player_id, :home_score, :away_score)
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]

  def index
    @players = Player.all
  end

  def new
    @player = Player.new
  end

  def show
    @player = Player.find(params[:id])
  end

  def create
    @player = Player.new(player_params)

    if @player.save
      flash[:notice] = "Player has been successfully added"
      redirect_to @player
    else
      flash.now[:alert] = "Player has not been added"
      render 'new'
    end
  end

  private
    def player_params
      params.require(:player).permit(:first_name, :last_name,
                                      :nickname, :avatar, :avatar_cache)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Foosballtrack
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      = render 'shared/errors'
      = render 'shared/navbar'
      = yield

app/views/matches/new.html.haml
.col-sm-6.col-sm-offset-3
  = simple_form_for @match do |f|
    = f.error_notification
    = f.input :match_date, as: :date_picker, :label => "Match Date"
    = f.association :home_player, label: "Home Player", label_method: :nickname, |
      value_method: :id                                                          |
    = f.input :home_score, collection: 1..10, label: 'Home Score'
    = f.association :away_player, label: "Away Player", label_method: :nickname, |
      value_method: :id                                                          |
    = f.input :away_score, collection: 1..10, label: 'Away Score'
    = f.error :base
    = f.button :submit, 'Add Match'

app/views/players/index.html.haml
.col-sm-12
  #carousel-example-generic.carousel.slide{"data-ride" => "carousel"}
    .carousel-inner{:role => "listbox"}
      .item.active
        .carousel-caption
        = image_tag 'pic1.jpg', class: "img-responsive center-block"
      .item
        .carousel-caption
        = image_tag 'pic2.jpg', class: "img-responsive center-block"
      .item
        .carousel-caption
        = image_tag 'pic3.jpg', class: "img-responsive center-block"
    %a.left.carousel-control{"data-slide" => "prev", :href => "#carousel-example-generic", :role => "button"}
      %span.glyphicon.glyphicon-chevron-left{"aria-hidden" => "true"}
      %span.sr-only Previous
    %a.right.carousel-control{"data-slide" => "next", :href => "#carousel-example-generic", :role => "button"}
      %span.glyphicon.glyphicon-chevron-right{"aria-hidden" => "true"}
      %span.sr-only Next


.col-sm-12
  %table.table.table-striped.table-hover
    %tr
      %th Nickname
      %th Number of Matches
      %th Wins
      %th Loses
      %th Goals
      %th Lost Goals
      %th Ranking

    - @players.each do |player|
      %tr
        %td= link_to player.nickname, player
        %td= player.number_of_matches
        %td= player.wins
        %td= player.lose
        %td= player.goals
        %td= player.lost_goals
        %td= "#{number_with_precision(player.rating, precision: 2)}"

app/views/players/new.html.haml
.col-sm-6.col-sm-offset-3
  %h1 New Player
  = simple_form_for @player do |f|
    = f.error_notification
    = f.input :nickname
    = f.input :first_name, label: "First Name"
    = f.input :last_name, label: "Last Name"
    = f.input :avatar, label: "Avatar", as: :file
    = f.input :avatar_cache, as: :hidden
    = f.button :submit, "Add Player"

app/views/players/show.html.haml
.container
  .panel-body.inf-content
    .row
      .col-md-4
        #player
          - if @player.avatar.present?
            .avatar
              = image_tag(@player.avatar_url, alt: "#{@player.nickname.downcase}")
          - else
            .avatar
              = image_tag(@player.avatar.default_url, size: "150x150")
          .usertitle
            .usertitle-name
              = "#{@player.full_name} aka #{@player.nickname} "
      .col-md-6
        = render 'shared/player', player: @player

app/views/shared/_errors.html.haml
.row
  .col-sm-offset-4.col-sm-4.text-center
    - flash.each do |key, message|
      %div{:class => "alert alert-#{key}"}
        = message

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-default.navbar-fixed-top{:role => "navigation"}
  .container
    .navbar-header
      .navbar-brand Foosball Tracker
    .navbar-right
      .btn-group.navbar-btn
        = link_to root_path, class: 'btn btn-default btn-sm' do
          %i.fa.fa-home
          Home
        - if user_signed_in?
          = link_to new_player_path, class: 'btn btn-default btn-sm' do
            %i.fa.fa-pencil.fa-fw
            New Player
          = link_to new_match_path, class: 'btn btn-default btn-sm' do
            %i.fa.fa-pencil.fa-fw
            New Match
          = link_to destroy_user_session_path, method: :delete, class: 'btn btn-default btn-sm' do
            %i.fa.fa-sign-out
            Sign Out
        - else
          = link_to new_user_registration_path, class: 'btn btn-default btn-sm' do
            %i.fa.fa-user-plus
            Sign Up
          = link_to new_user_session_path, class: 'btn btn-default btn-sm' do
            %i.fa.fa.fa-sign-in
            Sign In

app/views/shared/_player.html.haml
%strong Player Score Card
%br
  .table-responsive
    %table.table.table-condensed.table-responsive.table-user-information
      %tbody
        %tr
          %td
            %strong
              %span.fa.fa-male.fa-fw.text-primary
              First Name
          %td.text-primary
            = player.first_name
        %tr
          %td
            %strong
              %span.fa.fa-male.fa-fw.text-primary
              Last Name
          %td.text-primary
            = player.last_name
        %tr
          %td
            %strong
              %span.fa.fa-futbol-o.fa-fw.text-primary
              Number of Matches
          %td.text-primary
            = player.number_of_matches
        %tr
          %td
            %strong
              %span.fa.fa-trophy.fa-fw.text-primary
              Wins
          %td.text-primary
            = player.wins
        %tr
          %td
            %strong
              %span.fa.fa-meh-o.fa-fw.text-primary
              Loses
          %td.text-primary
            = player.lose
        %tr
          %td
            %strong
              %span.fa.fa-hand-o-up.fa-fw.text-primary
              Goals
          %td.text-primary
            = player.goals
        %tr
          %td
            %strong
              %span.fa.fa-hand-o-down.fa-fw.text-primary
              Lost Goals
          %td.text-primary
            = player.goals